// @ts-ignore
import videoSource from "../../public/僕らはまた.mp4";

export const bokuraWaMataData = {
    videoSource,
    title: "僕らはまた",
    artist: "Hinoha",
    lyrics: [
        { timeTag: "[00:00.67]", text: "既読スルーが溜まった月曜日", side: "left" as const },
        { timeTag: "[00:02.94]", text: "画面の光で「本当の自分」を隠して", side: "right" as const },
        { timeTag: "[00:07.49]", text: "SNSのタイムライン、誰かの「正解」を追いかけて", side: "left" as const },
        { timeTag: "[00:11.49]", text: "心は少しずつ 砂時計みたいに削れていく", side: "right" as const },
        { timeTag: "[00:16.48]", text: "「最近どう？」なんて、スタンプひとつで済ませる距離", side: "left" as const },
        { timeTag: "[00:20.98]", text: "でも今日は 特別な通知が鳴り響く", side: "right" as const },
        { timeTag: "[00:25.37]", text: "慣れ親しんだ名前 画面に躍る文字 「久しぶりに、あの場所で」", side: "left" as const },
        { timeTag: "[00:30.97]", text: "僕らはまた あの日に戻る", side: "right" as const, hasStamp: true },
        { timeTag: "[00:34.51]", text: "忘れかけていた確かな温もり抱きしめて", side: "left" as const },
        { timeTag: "[00:39.63]", text: "どんなことも 夜の静寂に溶けていく", side: "right" as const },
        { timeTag: "[00:44.71]", text: "君がいれば 世界はまだ 鮮やかに色づいてく", side: "left" as const },
        { timeTag: "[00:54.21]", text: "クローゼットの奥 お気に入りのシャツを選んで", side: "right" as const },
        { timeTag: "[00:57.65]", text: "鏡の前で あの頃みたいに", side: "left" as const },
        { timeTag: "[00:59.73]", text: "電車に揺られながら 思い出すのはあの場所", side: "right" as const },
        { timeTag: "[01:03.04]", text: "意味のない冗談で 笑い転げたあの日のこと", side: "left" as const },
        { timeTag: "[01:08.20]", text: "改札口 遠くに見える見覚えのある影", side: "right" as const },
        { timeTag: "[01:12.44]", text: "心拍数が BPMを追い越していく", side: "left" as const },
        { timeTag: "[01:15.68]", text: "一瞬で時を戻す 魔法の合言葉", side: "right" as const },
        { timeTag: "[01:19.29]", text: "心が晴れていく", side: "left" as const },
        { timeTag: "[01:22.56]", text: "僕らはまた あの日に戻る", side: "right" as const, hasStamp: true },
        { timeTag: "[01:25.93]", text: "忘れかけていた確かな温もり抱きしめて", side: "left" as const },
        { timeTag: "[01:30.96]", text: "どんなことも 夜の静寂に溶けていく", side: "right" as const },
        { timeTag: "[01:36.03]", text: "君がいれば 世界はまだ 鮮やかに色づいてく", side: "left" as const },
        { timeTag: "[01:44.33]", text: "レトロを未来に変えるような ステップ踏んで", side: "right" as const },
        { timeTag: "[01:47.96]", text: "「終わりがあるから今が尊い」って笑い合おう", side: "left" as const },
        { timeTag: "[01:51.56]", text: "それぞれの日常へ また明日から戻るけど", side: "right" as const },
        { timeTag: "[01:55.20]", text: "僕らの絆は みらいまで続く", side: "left" as const },
        { timeTag: "[01:59.29]", text: "僕らはまた あの日に戻る", side: "right" as const, hasStamp: true },
        { timeTag: "[02:02.97]", text: "忘れかけていた確かな温もり抱きしめて", side: "left" as const },
        { timeTag: "[02:07.69]", text: "どんなことも 夜の静寂に溶けていく", side: "right" as const },
        { timeTag: "[02:12.63]", text: "君がいれば 世界はまだ 鮮やかに色づいてく", side: "left" as const },
        { timeTag: "[02:21.87]", text: "「じゃあまたね」と手を振る背中に", side: "right" as const },
        { timeTag: "[02:24.77]", text: "新しい風が 吹き抜けていった", side: "left" as const },
        { timeTag: "[02:30.56]", text: "僕らはまた 走り出す", side: "right" as const },
    ],
};
