// @ts-ignore
import videoSource from "../../public/curtain_call.mp4";
import { staticFile } from "remotion";

export const curtainCallData = {
    title: "カーテンコール",
    artist: "",
    videoSource: staticFile("curtain_call.mp4"),
    lyrics: [
        { timeTag: "[00:00.86]", text: "画面の中　ピエロが踊る" },
        { timeTag: "[00:06.18]", text: "「いいね」の数が　僕の全て" },
        { timeTag: "[00:10.92]", text: "踊り続けた日々" },
        { timeTag: "[00:13.97]", text: "気づけば　今日も一人" },
        { timeTag: "[00:21.71]", text: "増えるフォロワー　でもこの虚しさはなに？" },
        { timeTag: "[00:25.07]", text: "誰かを叩けば　喜ぶ世界" },
        { timeTag: "[00:27.53]", text: "画面の奥で笑ってる　君は誰？" },
        { timeTag: "[00:32.42]", text: "画面の向こう　知らない誰か" },
        { timeTag: "[00:34.92]", text: "目の前にいる　君が見えない" },
        { timeTag: "[00:37.92]", text: "道化師（ピエロ）は　今日も笑い続ける" },
        { timeTag: "[00:42.60]", text: "本当の顔　どこへ行った" },
        { timeTag: "[00:46.14]", text: "スワイプする指　止まらない" },
        { timeTag: "[00:48.57]", text: "このままじゃダメだ　わかってるのに" },
        { timeTag: "[00:53.57]", text: "インスタ　Ｘ　終わらないショー" },
        { timeTag: "[00:56.24]", text: "バズることだけ　考えてた" },
        { timeTag: "[00:58.92]", text: "誰かを幸せに　したかっただけ" },
        { timeTag: "[01:01.42]", text: "なのに　幸せなのは誰？" },
        { timeTag: "[01:04.40]", text: "通知の音に　隠れた声" },
        { timeTag: "[01:09.80]", text: "「ねえ、楽しい？」" },
        { timeTag: "[01:11.60]", text: "君の言葉　遠くで響く" },
        { timeTag: "[01:15.54]", text: "涙を流した君　誰のために頑張ってるの？" },
        { timeTag: "[01:20.25]", text: "君を見つめた　その瞬間に" },
        { timeTag: "[01:23.03]", text: "欲しかった笑顔が　そこにあった" },
        { timeTag: "[01:25.75]", text: "画面じゃない　この世界に" },
        { timeTag: "[01:29.94]", text: "もう終わりにしよう　デジタルのショー" },
        { timeTag: "[01:33.00]", text: "ログアウトして　いいんだよ" },
        { timeTag: "[01:35.95]", text: "目の前にいる　大切な人" },
        { timeTag: "[01:38.59]", text: "それが全て" },
        { timeTag: "[02:02.99]", text: "カーテンコール　さあ幕を下ろそう" },
        { timeTag: "[02:07.98]", text: "画面を閉じて　君を見よう" },
        { timeTag: "[02:13.45]", text: "追い求めてた　幸せは" },
        { timeTag: "[02:17.95]", text: "ずっとここに　あったんだ" },
        { timeTag: "[02:24.03]", text: "もう自由だよ　さあピエロさん" },
        { timeTag: "[02:28.09]", text: "仮面を外して　目の前の世界" },
        { timeTag: "[02:30.62]", text: "本当の笑顔　輝いてる" },
        { timeTag: "[02:33.59]", text: "君と僕の　この世界（リアル）で" },
        { timeTag: "[02:38.30]", text: "ありがとう　そしてさよなら" },
        { timeTag: "[02:47.18]", text: "デジタルのピエロさん" },
        { timeTag: "[02:49.93]", text: "これからは　この手で" },
        { timeTag: "[02:54.67]", text: "目の前の君を　笑顔にするよ" }
    ]
};
