import { staticFile } from "remotion";

const videoSource = staticFile("仮面舞踏会.mp4");

export const kamenButokaiData = {
    videoSource,
    title: "仮面舞踏会",
    artist: "",
    lyrics: [
        { timeTag: "[00:14.09]", text: "手のひらで回る 終わらない舞踏会", side: "left" as const },
        { timeTag: "[00:17.96]", text: "「理想の私」演じて 踊り続けるの", side: "right" as const },
        { timeTag: "[00:20.72]", text: "通知のファンファーレ 止まらない喝采", side: "left" as const },
        { timeTag: "[00:22.86]", text: "みんなが言うの 「素敵なドレスね」って", side: "right" as const },
        { timeTag: "[00:30.22]", text: "画面消せば 魔法は解けて", side: "left" as const },
        { timeTag: "[00:32.00]", text: "散らかった部屋 静寂のバックステージ", side: "right" as const },
        { timeTag: "[00:35.18]", text: "「サヨナラ」告げた 彼の背中と", side: "left" as const },
        { timeTag: "[00:37.21]", text: "一人ぼっちの 冷めたディナー", side: "right" as const },
        { timeTag: "[00:41.13]", text: "輝くアイコン 煌めく虚構", side: "left" as const },
        { timeTag: "[00:42.82]", text: "仮面姿の 私が微笑む", side: "right" as const },
        { timeTag: "[00:46.33]", text: "完璧なステップ でも奥が痛むの", side: "left" as const },
        { timeTag: "[00:49.69]", text: "仮面のない私… それは私？", side: "right" as const },
        { timeTag: "[00:53.35]", text: "自分が誰か わからない", side: "left" as const },
        { timeTag: "[00:59.20]", text: "もう この曲に合わせて踊れない", side: "right" as const },
        { timeTag: "[01:02.17]", text: "誰かの期待 振りほどきたいのに", side: "left" as const },
        { timeTag: "[01:04.75]", text: "震える指先 仮面に触れて", side: "right" as const },
        { timeTag: "[01:07.74]", text: "ホールの出口で 躊躇ってる", side: "left" as const },
        { timeTag: "[01:09.99]", text: "このドアを開けるのが 怖いから", side: "right" as const },
        { timeTag: "[01:21.03]", text: "傷つくことから 逃げ回って", side: "left" as const },
        { timeTag: "[01:23.23]", text: "作り笑いの ドレスを纏った", side: "right" as const },
        { timeTag: "[01:25.29]", text: "でもその重さに 押しつぶされて", side: "left" as const },
        { timeTag: "[01:26.99]", text: "息をするのも 苦しいの", side: "right" as const },
        { timeTag: "[01:36.00]", text: "張り付いた嘘が 肌に食い込む", side: "left" as const },
        { timeTag: "[01:38.83]", text: "痛いよ 怖いよ でも", side: "right" as const },
        { timeTag: "[01:40.09]", text: "重たい扉の 隙間から", side: "left" as const },
        { timeTag: "[01:42.30]", text: "夜風が頬を 撫でていく", side: "right" as const },
        { timeTag: "[01:46.88]", text: "今ならきっと…！", side: "center" as const },
        { timeTag: "[01:50.85]", text: "誰かのステップなんて 踏まない", side: "left" as const },
        { timeTag: "[01:53.07]", text: "私はここで 踊るのをやめる", side: "right" as const },
        { timeTag: "[01:55.75]", text: "たとえあなたが ホールに残っても", side: "left" as const },
        { timeTag: "[01:58.54]", text: "ドレスを脱ぎ捨て 生きていく", side: "right" as const },
        { timeTag: "[02:01.14]", text: "涙も傷も 抱きしめて", side: "left" as const },
        { timeTag: "[02:20.67]", text: "Unmasked, I'm real.", side: "center" as const },
        { timeTag: "[02:21.84]", text: "喧騒を背に 歩き出す", side: "left" as const },
        { timeTag: "[02:23.77]", text: "冷たい風が 心地いい", side: "right" as const },
        { timeTag: "[02:25.40]", text: "これが本当の 世界", side: "left" as const },
        { timeTag: "[02:27.42]", text: "これが本当の 私", side: "center" as const },
    ],
};
