// @ts-ignore
import videoSource from "./神様のイタズラ完成版.mp4";

export const kamisamaData = {
    videoSource,
    lyrics: [
        { timeTag: "[00:00.67]", text: "click　click　光る画面" },
        { timeTag: "[00:02.13]", text: "perfect plan, perfect world" },
        { timeTag: "[00:04.47]", text: "なのに胸のどこかだけ" },
        { timeTag: "[00:08.01]", text: "バグったまんま" },
        { timeTag: "[00:11.21]", text: "ネオンの雨をくぐるハイヒール" },
        { timeTag: "[00:14.54]", text: "摩天楼を映すガラスのスーツ" },
        { timeTag: "[00:18.42]", text: "スペック最強　肩書きフル装備" },
        { timeTag: "[00:22.39]", text: "なのに small talk だけ赤点" },
        { timeTag: "[00:26.15]", text: "通知音が夜を埋めても" },
        { timeTag: "[00:28.49]", text: "心だけオフラインのまま" },
        { timeTag: "[00:30.98]", text: "笑い声が近づくたびに" },
        { timeTag: "[00:34.61]", text: "視界が急にノイズまみれ" },
        { timeTag: "[00:38.61]", text: "そんな calibration 外れた世界に" },
        { timeTag: "[00:41.01]", text: "急行列車がブレーキをかける" },
        { timeTag: "[00:43.20]", text: "ビルの海から　田んぼの波へ" },
        { timeTag: "[00:45.45]", text: "風景ごと soft reset" },
        { timeTag: "[00:48.31]", text: "あえてこんな世界　見せてくるのは" },
        { timeTag: "[00:50.81]", text: "きっと神様のイタズラでしょ" },
        { timeTag: "[00:52.88]", text: "ネオンと稲穂　同じ空の下" },
        { timeTag: "[00:55.30]", text: "logic じゃ選べない方角" },
        { timeTag: "[00:57.17]", text: "転びそうな heart に" },
        { timeTag: "[00:59.27]", text: "わざと小石を置いてくる" },
        { timeTag: "[01:01.81]", text: "No algorithm for love" },
        { timeTag: "[01:03.79]", text: "そんなステージが　ちょっとおもしろい" },
        { timeTag: "[01:06.90]", text: "Wi-Fi 途切れた小さな駅前" },
        { timeTag: "[01:09.56]", text: "長靴の泥がきらりと光る" },
        { timeTag: "[01:11.59]", text: "マニュアルにない笑い声だけが" },
        { timeTag: "[01:13.92]", text: "やけにクリアに響いてる" },
        { timeTag: "[01:15.22]", text: "効率悪い手仕事の午後" },
        { timeTag: "[01:17.39]", text: "ゆっくり回る扇風機の影" },
        { timeTag: "[01:18.98]", text: "予定調和じゃない沈黙が" },
        { timeTag: "[01:21.16]", text: "知らない rhythm を刻みだす" },
        { timeTag: "[01:22.84]", text: "誰かのバグに　誰かの笑い声" },
        { timeTag: "[01:25.17]", text: "ぎこちない手と手の distance" },
        { timeTag: "[01:26.85]", text: "説明書には書いてないルートを" },
        { timeTag: "[01:29.27]", text: "なぜか足が選んでく" },
        { timeTag: "[01:32.48]", text: "あえてこんな世界　混ぜてくるのは" },
        { timeTag: "[01:34.90]", text: "たぶん神様のユーモアでしょ" },
        { timeTag: "[01:36.78]", text: "shortcut だらけの人生マップに" },
        { timeTag: "[01:39.19]", text: "わざと遠回りの印" },
        { timeTag: "[01:41.11]", text: "完璧じゃない code に" },
        { timeTag: "[01:43.15]", text: "そっと “好き” をコメントしてくる" },
        { timeTag: "[01:45.54]", text: "No algorithm for love" },
        { timeTag: "[01:47.53]", text: "デバッグ中でも　再生ボタンは play" },
        { timeTag: "[01:57.25]", text: "雲の上で誰かが" },
        { timeTag: "[01:59.22]", text: "「そろそろ崩してみようか」と" },
        { timeTag: "[02:01.37]", text: "ピースをひとつ　入れ替えたみたいな" },
        { timeTag: "[02:03.95]", text: "タイミングの悪さがちょうどいい" },
        { timeTag: "[02:05.17]", text: "正解なんて退屈で" },
        { timeTag: "[02:07.13]", text: "伏線回収もいらないよ" },
        { timeTag: "[02:08.82]", text: "オチのない会話の続きから" },
        { timeTag: "[02:11.13]", text: "次の scene が始まる" },
        { timeTag: "[02:16.48]", text: "あえてこんな世界　渡してくるのは" },
        { timeTag: "[02:18.73]", text: "きっと神様の悪ノリでしょ" },
        { timeTag: "[02:20.67]", text: "ネオンの夜も　夕焼けの帰り道も" },
        { timeTag: "[02:23.06]", text: "どっちも main story" },
        { timeTag: "[02:25.04]", text: "転びそうな heart を" },
        { timeTag: "[02:27.13]", text: "何度も立たせて笑ってる" },
        { timeTag: "[02:29.35]", text: "No algorithm for love" },
        { timeTag: "[02:31.47]", text: "バグだらけのまま　アップデートしていく" },
        { timeTag: "[02:35.34]", text: "click　click　画面を閉じて" },
        { timeTag: "[02:37.38]", text: "耳をすませば breathe & laugh" },
        { timeTag: "[02:39.46]", text: "いたずらみたいなこの世界ごと" },
        { timeTag: "[02:41.87]", text: "好きになれたら　game on" },
    ],
};
