import { staticFile } from "remotion";

export const mikanseiNoChizuData = {
    videoSource: staticFile("未完成の地図.mp4"),
    title: "未完成の地図",
    artist: "",
    lyrics: [
        { timeTag: "[00:04.49]", text: "静まりかえった午前二時 窓に映る自分の影と目が合う" },
        { timeTag: "[00:10.51]", text: "街の明かりが遠くに見えて" },
        { timeTag: "[00:14.53]", text: "世界に取り残されたような気がした" },
        { timeTag: "[00:24.01]", text: "ペン先が刻む小さな音だけが 今の僕を証明している" },
        { timeTag: "[00:31.00]", text: "真っ白なページに書き込んだ迷いは いつか" },
        { timeTag: "[00:35.07]", text: "誰にも負けない答えに変わるかな" },
        { timeTag: "[00:41.44]", text: "「これでいいのか」なんて 投げ出したくなる夜もあるけれど" },
        { timeTag: "[00:46.33]", text: "君が灯したその小さな光を" },
        { timeTag: "[00:49.03]", text: "一番近くで　未来の" },
        { timeTag: "[00:53.07]", text: "君が見つめている" },
        { timeTag: "[00:58.33]", text: "走り出せ　まだ誰も知らない場所へ", isEmphasis: true },
        { timeTag: "[01:04.28]", text: "その足跡が　いつか道になるから" },
        { timeTag: "[01:09.17]", text: "今はまだ　答えが見えなくてもいい" },
        { timeTag: "[01:12.82]", text: "震える手で　明日への扉を叩け" },
        { timeTag: "[01:17.51]", text: "孤独の数は　強さの証明" },
        { timeTag: "[01:20.44]", text: "夜明けの向こうで　最高の景色が待っている", isEmphasis: true },
        { timeTag: "[01:28.14]", text: "SNSを閉じて　深呼吸した" },
        { timeTag: "[01:32.00]", text: "隣の芝生が青く見えても" },
        { timeTag: "[01:34.20]", text: "君が歩んでいるその泥臭い日々は" },
        { timeTag: "[01:37.75]", text: "誰にも真似できない　宝石の原石だ" },
        { timeTag: "[01:43.68]", text: "他人（だれか）が引いた　安全な境界線" },
        { timeTag: "[01:46.65]", text: "飛び越えるのは　少し怖いけれど" },
        { timeTag: "[01:49.64]", text: "積み上げた時間は　裏切りはしない" },
        { timeTag: "[01:52.88]", text: "風を切って　自分を信じて" },
        { timeTag: "[01:59.25]", text: "一人じゃないなんて　綺麗事かな？" },
        { timeTag: "[02:01.49]", text: "だけど　同じ月を見上げている仲間（ライバル）が" },
        { timeTag: "[02:04.85]", text: "どこかで　拳を握りしめている" },
        { timeTag: "[02:08.57]", text: "その熱さが　君の背中をそっと押すはず" },
        { timeTag: "[02:18.15]", text: "走り出せ　まだ誰も知らない場所へ", isEmphasis: true },
        { timeTag: "[02:24.08]", text: "その足跡が　いつか道になるから" },
        { timeTag: "[02:29.07]", text: "今はまだ　答えが見えなくてもいい" },
        { timeTag: "[02:32.72]", text: "震える手で　明日への扉を叩け" },
        { timeTag: "[02:37.09]", text: "孤独の数は　強さの証明" },
        { timeTag: "[02:40.40]", text: "夜明けの向こうで　最高の景色が待っている", isEmphasis: true },
        { timeTag: "[02:50.62]", text: "さあ、顔を上げて", isFinal: true },
        { timeTag: "[02:53.25]", text: "新しい風が　今吹き抜ける", isFinal: true },
        { timeTag: "[02:56.14]", text: "君だけの地図を　描き続けよう", isFinal: true },
        { timeTag: "[03:02.98]", text: "ほら、夜が明ける", isFinal: true },
    ],
};
