/* eslint-disable no-irregular-whitespace */
import { staticFile } from "remotion";

export const scarsIntoStarsData = {
    title: "Scars into Stars",
    artist: "Suno AI",
    videoSource: staticFile("suno_PJ/done/Scars into Stars.mp3"),
    lyrics: [
        { timeTag: "[00:00.67]", text: "おとぎ話で見た ガラスの城" },
        { timeTag: "[00:04.85]", text: "ここは息が止まるほど冷たい" },
        { timeTag: "[00:09.97]", text: "魔法の杖なんて 最初からない" },
        { timeTag: "[00:14.33]", text: "あるのは 擦り切れた踵（かかと）" },
        { timeTag: "[00:16.29]", text: "隠しきれない 青いあざの地図だけ" },
        { timeTag: "[00:21.05]", text: "何度も氷を叩いて 重力が私を縛る" },
        { timeTag: "[00:25.62]", text: "「もうやめたい」とこぼして" },
        { timeTag: "[00:27.78]", text: "白い息さえ 凍りついて" },
        { timeTag: "[00:30.32]", text: "あの頃の私が まだ私を睨んでる" },
        { timeTag: "[00:35.32]", text: "「ここで終わるために 泣いたわけじゃない」" },
        { timeTag: "[00:39.78]", text: "いま 夢にまで見た舞台に立つ" },
        { timeTag: "[00:44.20]", text: "スポットライトが 過去の影を焼き尽くしていく" },
        { timeTag: "[00:48.97]", text: "震える指先 解けないように結んだのは" },
        { timeTag: "[00:53.48]", text: "ただのひもじゃない みんなの願いだ" },
        { timeTag: "[00:58.11]", text: "傷だらけの足で 私は今日、光になる" },
        { timeTag: "[01:07.41]", text: "派手な衣装（ドレス）に隠した 無数の傷" },
        { timeTag: "[01:11.75]", text: "それは誰も知らない 私だけの勲章" },
        { timeTag: "[01:16.48]", text: "華やかに見える この数分間（とき）のために" },
        { timeTag: "[01:20.49]", text: "何度も 暗闇をさまよってきた" },
        { timeTag: "[01:24.85]", text: "一人きりの戦場だと ずっと思っていた" },
        { timeTag: "[01:29.00]", text: "耳を塞いで 孤独を愛そうとした" },
        { timeTag: "[01:33.72]", text: "だけど聞こえる 息をのむ音" },
        { timeTag: "[01:36.03]", text: "背中に感じる 声援が" },
        { timeTag: "[01:38.64]", text: "一人じゃきっと ここにはいない" },
        { timeTag: "[01:43.43]", text: "跳ぶよ 銀色のリンクを駆ける" },
        { timeTag: "[01:47.45]", text: "重力から解放されて 舞い上がる" },
        { timeTag: "[01:52.27]", text: "転んだ数が ここまで連れてきた" },
        { timeTag: "[01:57.14]", text: "冷たい痛みも 全部連れて行く" },
        { timeTag: "[02:01.37]", text: "この一瞬が 永遠に変わる場所へ Scars into Stars..." },
        { timeTag: "[02:11.53]", text: "一瞬の迷いが 運命を分けるなら" },
        { timeTag: "[02:15.18]", text: "私は迷わない エッジが描く軌跡を信じて" },
        { timeTag: "[02:19.95]", text: "積み上げた日々が 私の刃" },
        { timeTag: "[02:25.04]", text: "さあ、行こう 誰も見たことのない景色へ" },
        { timeTag: "[02:31.86]", text: "いま　夢の舞台で　あなたに返していく　もらった熱を" },
        { timeTag: "[02:36.52]", text: "スポットライトより 眩しい景色がここにあった" },
        { timeTag: "[02:40.78]", text: "震える心で 確かに掴んだものは" },
        { timeTag: "[02:45.39]", text: "私だけのじゃない みんなの願いだ" },
        { timeTag: "[02:49.97]", text: "傷跡はいま 星座になって輝く Scars into Stars..." },
    ],
};