/* eslint-disable no-irregular-whitespace */
import { staticFile } from "remotion";

export const yukitokenoLoveLetterData = {
    title: "雪解けのラブレター",
    artist: "Mio",
    videoSource: staticFile("雪解けのラブレター.mp4"),
    fontSize: 42,
    bottomOffset: 110,
    lyrics: [
        { timeTag: "[00:01.32]", text: "打ちかけた文字 また消した" },
        { timeTag: "[00:05.69]", text: "指が止まる 外はまだ冬" },
        { timeTag: "[00:12.13]", text: "白い息が 交差する朝" },
        { timeTag: "[00:17.85]", text: "おはようだけで 精一杯" },
        { timeTag: "[00:23.36]", text: "目が合いそうで 逸らした画面" },
        { timeTag: "[00:28.52]", text: "こっそり残した マフラーの君" },
        { timeTag: "[00:34.02]", text: "いいねの代わりに ため息ひとつ" },
        { timeTag: "[00:39.92]", text: "心だけ 近づいてく" },
        { timeTag: "[00:45.10]", text: "雪解けを ずっと待ってた" },
        { timeTag: "[00:50.10]", text: "春が来たら送ろう あの言葉" },
        { timeTag: "[00:56.03]", text: "溢れ出す気持ち もう止められない" },
        { timeTag: "[01:02.57]", text: "冷えた手のひらが 今 熱くなる" },
        { timeTag: "[01:15.89]", text: "下書きばかり 何度も書き直す" },
        { timeTag: "[01:21.28]", text: "フィルターじゃ隠せないよ" },
        { timeTag: "[01:27.18]", text: "ぎこちない言葉でいい" },
        { timeTag: "[01:30.82]", text: "飾らなくていい ありのまま" },
        { timeTag: "[01:39.00]", text: "あのね 知ってるよ" },
        { timeTag: "[01:42.17]", text: "春が来たら 会えなくなるかも" },
        { timeTag: "[01:45.04]", text: "だからこそ今" },
        { timeTag: "[01:47.63]", text: "この想い ぜんぶ詰め込む" },
        { timeTag: "[01:51.34]", text: "雪解けのラブレター 震える指で" },
        { timeTag: "[01:57.45]", text: "最後の冬に 綴るメッセージ" },
        { timeTag: "[02:01.82]", text: "水たまりに映る 空を踏み抜いて" },
        { timeTag: "[02:07.52]", text: "嫌われてもいい 知ってほしいだけ" },
        { timeTag: "[02:14.07]", text: "母の引き出し 色あせた便箋" },
        { timeTag: "[02:19.18]", text: "あんなふうに 私も震えてるかな" },
        { timeTag: "[02:24.47]", text: "書いたことないけど" },
        { timeTag: "[02:30.13]", text: "この画面の文字が 私のラブレター" },
        { timeTag: "[02:40.09]", text: "さあ送り出そう" },
        { timeTag: "[02:42.46]", text: "怖いよ でも このまま溶けるよりは" },
        { timeTag: "[02:47.89]", text: "たった一通の ラブレター" },
        { timeTag: "[02:53.33]", text: "凍えた季節に サヨナラ" },
        { timeTag: "[03:08.65]", text: "にじんだ画面 外はもう春" },
        { timeTag: "[03:15.08]", text: "私の春が 今…はじまる" },
    ]
};
